-- Ejecuta este script en Supabase SQL Editor
-- Crea tabla pública para leaderboard del juego

create table if not exists public.leaderboard_scores (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 20),
  score integer not null check (score >= 0),
  mode text not null check (mode in ('normal', 'infinito')),
  level_reached integer,
  created_at timestamptz not null default now()
);

create index if not exists leaderboard_scores_mode_score_idx
  on public.leaderboard_scores (mode, score desc, created_at asc);

alter table public.leaderboard_scores enable row level security;

-- Lectura pública para cualquiera que entre al link
drop policy if exists "public read leaderboard"
on public.leaderboard_scores;

create policy "public read leaderboard"
on public.leaderboard_scores
for select
using (true);

-- Inserción pública controlada por checks de tabla
drop policy if exists "public insert leaderboard"
on public.leaderboard_scores;

create policy "public insert leaderboard"
on public.leaderboard_scores
for insert
with check (true);
